# app/modules/ai_ml/threshold_analyzer.py
"""
The threshold analyzer monitors the fatigue score generated by the model and triggers alerts based on predefined thresholds.

For simplicity, we'll set a threshold of 0.7 (70% fatigue) for issuing a warning.
This component takes the fatigue score from the model and compares it against a threshold to return an appropriate alert message.
"""

class ThresholdAnalyzer:
    def __init__(self, threshold=0.7):
        self.threshold = threshold
    
    def analyze(self, fatigue_score):
        """Analyze the fatigue score and return whether an alert is needed."""
        if fatigue_score >= self.threshold:
            return "Critical Fatigue Detected"
        elif fatigue_score >= self.threshold - 0.1:
            return "Take a Break"
        else:
            return "Alertness Normal"
